name: 'Unet'

train_dir: './src/dataset/PDImpression/train'
train_gt_dir: './src/dataset/PDImpression/train_gt'
val_train_dir: './src/dataset/PDImpression/val'
val_gt_dir: './src/dataset/PDImpression/val_gt'
save_path: './save/Wear_detection/PDImpression/gt'

batch_size: 2
epochs: 100
learning_rate: 0.00005
